global:
  config_name: preprocess_GVC_dev

pipeline:
  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: True
      gvc_split_csv_filename: "dev.csv"

#  - python.handwritten_baseline.pipeline.data.processing.reducer:
#      num_topics: 2
#      num_docs_per_topic: 25

  - python.handwritten_baseline.pipeline.data.processing.corenlp_pos_ner:
      mode: extend

  - python.handwritten_baseline.pipeline.data.processing.timex_parse:

  - python.handwritten_baseline.pipeline.data.processing.entity_linking.dbpedia_spotlight:
      mode: extend

  - python.handwritten_baseline.pipeline.data.processing.entity_linking.location_enhance:

  - python.handwritten_baseline.pipeline.data.processing.srl: