global:
  config_name: ecbp_stats

pipeline:
  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/train"

      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"

  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/valid"

      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"

  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/test"

      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"

  - python.handwritten_baseline.pipeline.data.processing.reducer:
      drop_sentences_without_action_mentions: True

  - python.handwritten_baseline.pipeline.data.processing.corenlp_pos_ner:
      mode: extend
      keep_dependency_trees: True
      keep_constituency_trees: True

  - python.handwritten_baseline.pipeline.data.processing.statistics:
      write_general_statistics: True
      write_stacked_annotations: False
      write_selection_of_clusters: True
      write_selection_of_full_documents: True
      write_most_common_phrase_types_of_mentions: True
      write_action_mention_span_length: True
      write_phrase_head_statistics: True
      write_mention_pos_occurrence: True
      write_cluster_entropy_statistics: True
