global:
  config_name: gvc_stats

pipeline:
  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: False
      gvc_split_csv_filename: "train.csv"

  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: False
      gvc_split_csv_filename: "dev.csv"

  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: False
      gvc_split_csv_filename: "test.csv"

  - python.handwritten_baseline.pipeline.data.processing.reducer:
      drop_sentences_without_action_mentions: True

  - python.handwritten_baseline.pipeline.data.processing.corenlp_pos_ner:
      mode: extend
      keep_dependency_trees: True
      keep_constituency_trees: True

  - python.handwritten_baseline.pipeline.data.processing.statistics:
      write_general_statistics: True
      write_stacked_annotations: False
      write_selection_of_clusters: True
      write_selection_of_full_documents: True
      write_most_common_phrase_types_of_mentions: True
      write_action_mention_span_length: True
      write_phrase_head_statistics: True
      write_mention_pos_occurrence: True
      write_cluster_entropy_statistics: True