# common dataset constants
COLLECTION = "collection"
TOPIC_ID = "topic-id"
SUBTOPIC = "subtopic"
DOCUMENT_ID = "doc-id"
DOCUMENT_NUMBER = "doc-number"
EVENT = "event"
EVENT_ID = "event-id"
ENTITY = "entity"
ENTITY_ID = "entity-id"
MENTION_ID = "mention-id"
TOKEN = "token"
TOKEN_IDX = "token-idx"
SENTENCE = "sentence"
SENTENCE_IDX = "sentence-idx"
SENTENCE_TYPE = "sentence-type"
MENTION_TYPE = "mention-type"
DESCRIPTION = "description"
PUBLISH_DATE = "publish-date"

# specifics for span-based data
CHARS_START = "chars-start"
CHARS_END = "chars-end"
TOKEN_IDX_FROM = "token-idx-from"
TOKEN_IDX_TO = "token-idx-to"

# football-dataset specific
MENTIONS_CS = "mentions-cross-subtopic"
MENTIONS_SEMINAL = "mentions-seminal-event"
MENTIONS_STOOO = "mentions-same-type-out-of-ontology"
SEMINAL_EVENT = "seminal-event"
CONTEXT_OF_SENTENCE = "sentence-context"
CONTEXT_OF_DOCUMENT = "document-context"

# mention types
ACTION_ASPECTUAL = "ACTION_ASPECTUAL"
ACTION_CAUSATIVE = "ACTION_CAUSATIVE"
ACTION_GENERIC = "ACTION_GENERIC"
ACTION_OCCURRENCE = "ACTION_OCCURRENCE"
ACTION_PERCEPTION = "ACTION_PERCEPTION"
ACTION_REPORTING = "ACTION_REPORTING"
ACTION_STATE = "ACTION_STATE"
NEG_ACTION_ASPECTUAL = "NEG_ACTION_ASPECTUAL"
NEG_ACTION_CAUSATIVE = "NEG_ACTION_CAUSATIVE"
NEG_ACTION_GENERIC = "NEG_ACTION_GENERIC"
NEG_ACTION_OCCURRENCE = "NEG_ACTION_OCCURRENCE"
NEG_ACTION_PERCEPTION = "NEG_ACTION_PERCEPTION"
NEG_ACTION_REPORTING = "NEG_ACTION_REPORTING"
NEG_ACTION_STATE = "NEG_ACTION_STATE"
MENTION_TYPES_ACTION_NEGATED = [NEG_ACTION_ASPECTUAL, NEG_ACTION_CAUSATIVE, NEG_ACTION_GENERIC, NEG_ACTION_OCCURRENCE, NEG_ACTION_PERCEPTION, NEG_ACTION_REPORTING, NEG_ACTION_STATE]
MENTION_TYPES_ACTION_NONNEGATED = [ACTION_ASPECTUAL, ACTION_CAUSATIVE, ACTION_GENERIC, ACTION_OCCURRENCE, ACTION_PERCEPTION, ACTION_REPORTING, ACTION_STATE]
MENTION_TYPES_ACTION = MENTION_TYPES_ACTION_NEGATED + MENTION_TYPES_ACTION_NONNEGATED
TIME_DATE = "TIME_DATE"
TIME_REPETITION = "TIME_REPETITION"
TIME_OF_THE_DAY = "TIME_OF_THE_DAY"
TIME_DURATION = "TIME_DURATION"
MENTION_TYPES_TIME = [TIME_DATE, TIME_REPETITION, TIME_OF_THE_DAY, TIME_DURATION]
LOC_GEO = "LOC_GEO"
LOC_FAC = "LOC_FAC"
LOC_OTHER = "LOC_OTHER"
MENTION_TYPES_LOCATION = [LOC_GEO, LOC_FAC, LOC_OTHER]
HUMAN_PART_FAC = "HUMAN_PART_FAC"
HUMAN_PART_GPE = "HUMAN_PART_GPE"
HUMAN_PART_PER = "HUMAN_PART_PER"
HUMAN_PART_ORG = "HUMAN_PART_ORG"
HUMAN_PART_MET = "HUMAN_PART_MET"
HUMAN_PART_VEH = "HUMAN_PART_VEH"
HUMAN_PART_GENERIC = "HUMAN_PART_GENERIC"
NON_HUMAN_PART_GENERIC = "NON_HUMAN_PART_GENERIC"
NON_HUMAN_PART = "NON_HUMAN_PART"
MENTION_TYPES_PARTICIPANTS = [HUMAN_PART_FAC, HUMAN_PART_GPE, HUMAN_PART_PER, HUMAN_PART_ORG, HUMAN_PART_MET,
                              HUMAN_PART_VEH, HUMAN_PART_GENERIC, NON_HUMAN_PART_GENERIC, NON_HUMAN_PART]

# mapping from timex types reported from SUtime to the types we use
TIMEX_CORENLP_TO_OURS = {"DATE": TIME_DATE,
                         "DURATION": TIME_DURATION,
                         "SET": TIME_REPETITION,
                         "TIME": TIME_OF_THE_DAY}