global:
  config_name: preprocess_FCC-T_GVC_train_dev

pipeline:
  - python.handwritten_baseline.pipeline.data.loader.fcc_loader_token:
      sentence_level_data_dir: "resources/data/football/2020-10-05_FCC_cleaned/train"
      token_level_data_dir: "resources/data/football/2020-10-05_FCC-T/train/with_stacked_actions"

      drop_other_event_cluster: True

  - python.handwritten_baseline.pipeline.data.loader.fcc_loader_token:
      sentence_level_data_dir: "resources/data/football/2020-10-05_FCC_cleaned/dev"
      token_level_data_dir: "resources/data/football/2020-10-05_FCC-T/dev/without_stacked_actions"

      drop_other_event_cluster: True

  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: True
      gvc_split_csv_filename: "train.csv"

  - python.handwritten_baseline.pipeline.data.loader.gvc_loader:
      gvc_root_dir: "resources/data/gun_violence"
      drop_0_cluster: True
      gvc_split_csv_filename: "dev.csv"

  - python.handwritten_baseline.pipeline.data.processing.corenlp_pos_ner:
      mode: extend

  - python.handwritten_baseline.pipeline.data.processing.timex_parse:

  - python.handwritten_baseline.pipeline.data.processing.entity_linking.dbpedia_spotlight:
      mode: extend

  - python.handwritten_baseline.pipeline.data.processing.entity_linking.location_enhance:

  - python.handwritten_baseline.pipeline.data.processing.srl:

  - python.handwritten_baseline.pipeline.data.processing.feature_preparation.wikidata_embeddings:
      json_index: "resources/wikidata_embeddings/wikidata_translation_v1_names.json"
      embedding_npy: "resources/wikidata_embeddings/wikidata_translation_v1_vectors.npy"

  - python.handwritten_baseline.pipeline.data.processing.feature_preparation.sentence_bert_embeddings:
      pretrained_model_name: "distilbert-base-nli-stsb-mean-tokens"

  - python.handwritten_baseline.pipeline.data.processing.feature_preparation.action_phrase_embeddings:
      model: "resources/spanbert/model.tar.gz"

  - python.handwritten_baseline.pipeline.data.processing.dataset_exporter:
      dataset_name: fcct_gvc
      split: traindev