global:
  config_name: preprocess_gg_aug_bbc-fcct

pipeline:

  # load the dev and test splits of the to-be-augmented CDCR dataset (this will merge them into one dataset)

  # FCC-T
  - python.handwritten_baseline.pipeline.data.loader.fcc_loader_token:
      sentence_level_data_dir: "resources/data/football/2020-10-05_FCC_cleaned/dev"
      token_level_data_dir: "resources/data/football/2020-10-05_FCC-T/dev/without_stacked_actions"
      drop_other_event_cluster: True
  - python.handwritten_baseline.pipeline.data.loader.fcc_loader_token:
      sentence_level_data_dir: "resources/data/football/2020-10-05_FCC_cleaned/test"
      token_level_data_dir: "resources/data/football/2020-10-05_FCC-T/test/without_stacked_actions"
      drop_other_event_cluster: True

  # load hyperlink data, and use the 'difference' operation to remove all hyperlinks documents which are similar to
  # the datasets loaded prior
  - python.handwritten_baseline.pipeline.data.loader.hyperlinks_loader:
      page_infos: "resources/data/hypercoref/bbc.com/train/page_infos.parquet"
      tokens: "resources/data/hypercoref/bbc.com/train/tokens.parquet"
      hyperlinks: "resources/data/hypercoref/bbc.com/train/hyperlinks.parquet"

      # this here is crucial!
      combine_operation: "difference"
      combine_difference_threshold: 0.25

  - python.handwritten_baseline.pipeline.data.processing.reducer:
      event_cluster_size_interval_to_keep: [2, 10]

  - python.handwritten_baseline.pipeline.data.processing.hyperlinks_hack:
      constituency: "resources/data/hypercoref/bbc.com/constituency.hdf"
      dependency: "resources/data/hypercoref/bbc.com/dependency.hdf"

      drop_phrasal_mentions: False
      reduce_span_to_dependency_head: True

      target_num_docs_per_fake_topic: 50
      total_mentions_limit: 1500

  # add FCC-T here
  - python.handwritten_baseline.pipeline.data.loader.fcc_loader_token:
      sentence_level_data_dir: "resources/data/football/2020-10-05_FCC_cleaned/train"
      token_level_data_dir: "resources/data/football/2020-10-05_FCC-T/train/without_stacked_actions"

      drop_other_event_cluster: True

  - python.handwritten_baseline.pipeline.data.processing.dataset_exporter:
      dataset_name: gg_aug_bbc-fcct
      split: train
      export_in_cattan_format_as_well: True