global:
  config_name: preprocess_gg_aug_wired-ecbp

pipeline:

  # load the dev and test splits of the to-be-augmented CDCR dataset (this will merge them into one dataset)

  # ECB+
  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/valid"
      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"
  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/test"
      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"

  # load hyperlink data, and use the 'difference' operation to remove all hyperlinks documents which are similar to
  # the datasets loaded prior
  - python.handwritten_baseline.pipeline.data.loader.hyperlinks_loader:
      page_infos: "resources/data/hypercoref/wired.com/train/page_infos.parquet"
      tokens: "resources/data/hypercoref/wired.com/train/tokens.parquet"
      hyperlinks: "resources/data/hypercoref/wired.com/train/hyperlinks.parquet"

      # this here is crucial!
      combine_operation: "difference"
      combine_difference_threshold: 0.25

  - python.handwritten_baseline.pipeline.data.processing.reducer:
      event_cluster_size_interval_to_keep: [2, 10]

  - python.handwritten_baseline.pipeline.data.processing.hyperlinks_hack:
      constituency: "resources/data/hypercoref/wired.com/constituency.hdf"
      dependency: "resources/data/hypercoref/wired.com/dependency.hdf"

      drop_phrasal_mentions: False
      reduce_span_to_dependency_head: True

      target_num_docs_per_fake_topic: 50
      total_mentions_limit: 3800

  # add ECB+ here
  - python.handwritten_baseline.pipeline.data.loader.ecb_loader:
      path_to_data_split: "resources/data/ecbplus/train"
      sentence_filter_csv: "resources/data/ecbplus/ECBplus_coreference_sentences.csv"

  - python.handwritten_baseline.pipeline.data.processing.dataset_exporter:
      dataset_name: gg_aug_wired-ecbp
      split: train
      export_in_cattan_format_as_well: True